#!/bin/bash
nohup jupyter lab --ip 0.0.0.0 --no-browser --allow-root --NotebookApp.password='argon2:$argon2id$v=19$m=10240,t=10,p=8$YnARAfqAO3waqg1ScJWqDA$PFtrJ7qh5fs7FSl3w6hSx/HfT/sAKEqJqKHQfYrVD/Y' --port 8888 &> /dev/null &
